---
- name: Deploy application in the new namespace
  hosts: localhost

  tasks:
   - name: Create a k8s namespace
     k8s:
      name: my-app
      api_version: v1
      kind: Namespace
      state: present
#     kubeconfig: Path to an existing Kubernetes config file
    
   - name: Deploy nginx app
     k8s:
      src: nginx.yaml
      state: present
#     kubeconfig: Path to an existing Kubernetes config file, 
#     but it isn't necessary because ansible load kube config in the ~/.kube/config file
      namespace: my-app
      